# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c77c78062ffd0ff21c96a5d86a1e663cd792fb911af6224abfaeb19381b09201ac176998601e511f3a0b93dc52ceb7ee97d5e1042603b4c88bc7cbe41beb383

test:
  secret_key_base: bb3784eb6b8506c0d7010c8cadefe954196c07a9ff631b3e879bb68a3e4158f92a1112553419ce8d0c33c0d970a8cfa755b4275af2e295440d22f123bb7f532d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
